#!/bin/bash
#
# Copyright (c) 2004-2025 Matthew Pearson <matthewpearson@gmail.com>.
#
# These scripts are free. There is no warranty; your mileage may vary.
# Visit http://creativecommons.org/licenses/by-nc-sa/4.0/ for more details.
#
# print out battery statistics extracted from ioreg
#

[ -x /usr/sbin/ioreg ] || exit 1

OLDIFS="$IFS"
IFS='|'
fields=(
  'AbsoluteMaxCapacity'
  'AppleRawCurrentCapacity'
  'AppleRawMaxCapacity'
  'Capacity'
  'Current'
  'CurrentCapacity'
  'CycleCount'
  'Cycle_Count'
  'DesignCapacity'
  'Voltage'
)
joined_fields="${fields[*]}"
IFS="$OLDIFS"

# convert AppleSmartBattery device data into shell variable assignments
eval $(/usr/sbin/ioreg -c AppleSmartBattery -r AppleSmartBattery -w 0 | \
  sed -Ene 's/ *\"('"${joined_fields}"')\" = (\d*)/\1=\2/p')

[ "$Voltage" ] || Voltage="unknown"
echo -n "volts=$Voltage"

if [ "$CycleCount" ]
then
	echo -n ", cycles=$CycleCount"
elif [ "$Cycle_Count" ]
then
	echo -n ", cycles=$Cycle_Count"
fi

if [ "$CurrentCapacity" ]
then
	echo ", charge=$CurrentCapacity%	# $AppleRawCurrentCapacity/$AppleRawMaxCapacity of $DesignCapacity rated mAh"

elif [ "$Current" -a "$Capacity" -a "$AbsoluteMaxCapacity" ]
then
	pct1=$(echo "scale=1; 100 * $Current / $Capacity" | \
	  bc | sed 's/\.0//')
	pct2=$(echo "scale=1; 100 * $Current / $AbsoluteMaxCapacity" | \
	  bc | sed 's/\.0//')

	echo ", charge=$Current/$Capacity/$AbsoluteMaxCapacity ($pct1/$pct2%)"

elif [ "$Current" -a "$Capacity" ]
then
	pct=$(echo "scale=1; 100 * $Current / $Capacity" | \
	  bc | sed 's/\.0//')

	echo ", charge=$Current/$Capacity ($pct%)"

elif [ "$Current" ]
then
	echo ", charge=$Current"
else
	echo ", charge=unknown"
fi

#EOF __TAGGED__
