#!/bin/bash
#
# Copyright (c) 2025 Matthew Pearson <matthewpearson@gmail.com>.
#
# These scripts are free. There is no warranty; your mileage may vary.
# Visit http://creativecommons.org/licenses/by-nc-sa/4.0/ for more details.
#
# make a best guess as to what the name of a Mac is
#

[ -f /Library/Preferences/SystemConfiguration/preferences.plist ] || exit 1

# set THOST to the AppleTalk (user-chosen) name on Macs
RawHostNameData=$(defaults read /Library/Preferences/SystemConfiguration/preferences.plist System)
LocalHostName=$(echo "$RawHostNameData" \
  | grep 'LocalHostName = ' \
  | sed -e 's/^ *//' -e 's/;$//' -e 's/.* = //' -e 's/^"//' -e 's/"$//' \
  | uniq)
ComputerName=$(echo "$RawHostNameData" \
  | grep 'ComputerName = ' \
  | sed -e 's/^ *//' -e 's/;$//' -e 's/.* = //' -e 's/^"//' -e 's/"$//' \
  | uniq)
if [ "$LocalHostName" = "$ComputerName" ]
then
	THOST="$LocalHostName"
else
	# try to handle the "(3)" and "-2" AppleTalk name issues that got worse with Yosemite
	LocalHostName=${LocalHostName// *-[0-9][0-9]*/}
	ComputerName=${ComputerName// *([0-9][0-9]*)/}

	# Unicode characters and spaces present differently in these two variables
	AsciiLocalHostName=${LocalHostName//-/ }
	AsciiComputerName=${ComputerName//\\\\U[0-9]\{4,4\}/}

	# unescape smart single quotes from computer name
	# shellcheck disable=SC2059		# unicode literals must be in format string
	UnicodeComputerName=$(printf "${ComputerName//\\\\U2019/\\xe2\\x80\\x99}")

	if [ "$AsciiLocalHostName" = "$AsciiComputerName" ]
	then
		THOST="UnicodeComputerName"
	else
		THOST="${UnicodeComputerName} (${LocalHostName})"
	fi
fi

echo "$THOST"

#EOF __TAGGED__
