#!/bin/sh
#
# Copyright (c) 2003-2015 Matthew Pearson <matthewpearson@gmail.com>.
#
# These scripts are free. There is no warranty; your mileage may vary.
# Visit http://creativecommons.org/licenses/by-nc-sa/4.0/ for more details.
#
# $Id$
# print out information about the c compiler and make in $PATH
#

# inherit path from environment
PATH=$PATH:/usr/bin:/bin

. "$HOME/.isinstalled"

if [ `isinstalled gcc` ]
then
	gccver=`gcc -V 2>&1 | awk '/ C / {print}' | \
	  sed -e 's/cc: //' -e 's/ *on.*//'`
	[ "$gccver" ] || gccver=`gcc -v 2>&1 | grep '\bversion'`
	[ "$gccver" ] || gccver='unknown gcc'
	gccver=`echo $gccver | sed 's/version //'`
else
	[ "$gccver" ] || gccver='[ gcc not found ]'
fi

if [ `isinstalled make` ]
then
	make --version >/dev/null 2>&1
	if [ $? -eq 0 ]
	then
		makever='GNU make '`make --version | \
		  make --version | awk 'NR == 1 {print}' | \
		  sed -e 's/^[^0-9]*//' -e 's/[^0-9]*$//'`
	else
		makever='unix make'
	fi
else
	makever='[ make not found ]'
fi

javaver='[ java not found ]'
if [ `isinstalled java` ]
then
    bundle_version=`defaults read "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Info.plist" \
      CFBundleShortVersionString 2>/dev/null`
    if [ "$bundle_version" ]
    then
        javaver=`echo "$bundle_version" | tr '[A-Z]' '[a-z]'`
    else
        grep JavaInstallOnDemand \
          "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/version.plist" > \
          /dev/null 2>&1
        if [ $? -eq 0 ]
        then
            javaver='java not installed'
	    elif [ -d "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/" ] || [ `uname` != "Darwin" ]
	    then
		    javaver='java '`java -version 2>&1 | awk 'NR == 1 { print $3 }' | sed 's/\"//g'`
	    fi
	fi
fi

echo "$gccver / $makever / $javaver"

#EOF __TAGGED__
